  INSERT INTO dbo.LookupGeneral (ObjectCustomConfigID, Name, Value, TranslateValue, ListOrder, IsActive, CreateTime, CreatedBy) 
  VALUES (2, 'LaborQuoteLaborTypeValue', 'Reg', '49', 1, 1, GETDATE(), 'SYSTEM')
  INSERT INTO dbo.LookupGeneral (ObjectCustomConfigID, Name, Value, TranslateValue, ListOrder, IsActive, CreateTime, CreatedBy) 
  VALUES (2, 'LaborQuoteLaborTypeValue', 'OT', '98', 2, 1, GETDATE(), 'SYSTEM')
  INSERT INTO dbo.LookupGeneral (ObjectCustomConfigID, Name, Value, TranslateValue, ListOrder, IsActive, CreateTime, CreatedBy) 
  VALUES (2, 'LaborQuoteLaborTypeValue', 'DT', '73.50', 3, 1, GETDATE(), 'SYSTEM')
  INSERT INTO dbo.LookupGeneral (ObjectCustomConfigID, Name, Value, TranslateValue, ListOrder, IsActive, CreateTime, CreatedBy) 
  VALUES (2, 'LaborQuoteLaborTypeValue', 'PWR', '72', 4, 1, GETDATE(), 'SYSTEM')
  INSERT INTO dbo.LookupGeneral (ObjectCustomConfigID, Name, Value, TranslateValue, ListOrder, IsActive, CreateTime, CreatedBy) 
  VALUES (2, 'LaborQuoteLaborTypeValue', 'PWOT', '108', 5, 1, GETDATE(), 'SYSTEM')
  INSERT INTO dbo.LookupGeneral (ObjectCustomConfigID, Name, Value, TranslateValue, ListOrder, IsActive, CreateTime, CreatedBy) 
  VALUES (2, 'LaborQuoteLaborTypeValue', 'PWDT', '144', 6, 1, GETDATE(), 'SYSTEM')